---
output: html_document
#runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(
  tidyverse, shiny, magrittr,latex2exp
)


E = function(c,a_e,a_c,temp,u){
    exp((1/(a_e*temp))*(log(u) - a_c*log(c)))
}


ic_df = expand_grid(
  c = seq(0.5,5,by = 0.05),
  a_e = seq(0.5,5,by = 0.5),
  a_c = seq(0.5,5,by = 0.5),
  temp = seq(0.1,1,by = 0.1),
  u = 1:10
)
  
ic_df %<>% mutate(E = E(c,a_e,a_c,temp,u))
```

```{r ic_plot, echo = F, warning=F, fig.align='center', fig.width=8, fig.height=7}
ic_plot = 
  ic_df |>
  filter(a_e == 1 & a_c == 1 & u == 1) |>
  ggplot(aes(x = c, y = E, group = temp, color = temp)) + 
  geom_line() +
  scale_color_viridis_c(option = "magma", name = "Temp Index (T)", end = 0.8) +
  xlim(0,5) + 
  ylim(0,5) +
  theme_classic(base_size = 16) +
  labs(
    x = "Consumption",
    y = "Energy",
    title = TeX("Indifference Curves of $U = c^{\\alpha_c}E^{\\alpha_e T}$"),
    caption = TeX("For $U = 1, \\; \\alpha_c = 1, \\; \\alpha_e = 1$")
  )

ic_plot

```


```{r ic_shiny, echo=FALSE, eval = FALSE }
# Define UI for slider demo app ----
ui <- fluidPage(

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar to demonstrate various slider options ----
    sidebarPanel(
      sliderInput("a_c", label = "$\\alpha_c$:",
                  min = 0.2, max = 2, value = 1, step = 0.2),
      sliderInput("a_e", label = "$\\alpha_e$:",
                  min = 0.2, max = 2, value = 1, step = 0.2),
      sliderInput("temp", label = "Temp Index:",
                  min = 0, max = 1, value = 0.5, step = 0.1),
      sliderInput("u", label = "Utility Level:",
                  min = 0.2, max = 100, value = 1, step = 1)
    
  ),

    # Main panel for displaying outputs ----
    mainPanel(

      # Output: Table summarizing the values entered ----
      plotOutput("plotT")

    )
))


ui <- fluidPage(

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar to demonstrate various slider options ----
    sidebarPanel(
      # Input: Decimal interval with step value ----
      sliderInput("a_c", label = "$\\alpha_c$:",
                  min = 0.2, max = 2, value = 1, step = 0.2),
      sliderInput("a_e", label = "$\\alpha_e$:",
                  min = 0.2, max = 2, value = 1, step = 0.2),
      sliderInput("temp", label = "Temp Index:",
                  min = 0, max = 1, value = 0.5, step = 0.1),
      sliderInput("u", label = "Utility Level:",
                  min = 0.2, max = 100, value = 1, step = 1)
    ),

    # Main panel for displaying outputs ----
    mainPanel(

      # Output: Table summarizing the values entered ----
      plotOutput("plotT")

    )
  )

)

server <- function(input, output) {
output$plotT = renderPlot({
  

ic_df |>
  filter(
    a_e == input$a_e 
    & a_c == input$a_c
    & u == input$u
  ) |>
  ggplot(aes(x = c, y = E, group = temp, color = temp)) + 
  geom_line() +
  scale_color_viridis_c(
    option = "magma",
    name = "Temp Index",
    end = 0.75
    ) +
  xlim(0,5) + 
  ylim(0,5) +
  theme_classic() +
  labs(
    x = "Numeraire",
    y = "Energy",
    title = "Indifference Curves"
  )
})
}

# Create Shiny app ----
shinyApp(ui, server,options = list(height = 900) )
```





