---
title: ""
---

#### **Perinatal health effects of herbicides: Glyphosate, Roundup, and the rollout of GM crops** with [Ed Rubin](http://edrub.in/) 

The advent of herbicide-tolerant genetically modified (GM) crops led to rapid and widespread use of the herbicide glyphosate throughout US agriculture. In the two decades following GM-seed introduction, the volume of glyphosate used in the US increased by more than 750%. Despite glyphosate’s breadth and scale, science and policy remain unresolved re- garding its effects on human health. To identify the causal effect of glyphosate exposure on perinatal health, we combine (1) county-level variation in glyphosate use driven by (2) the timing of the release of GM technology and (3) differential geographic suitability for GM crops. Our results suggest glyphosate significantly reduces average birth weight and gestational length. We find effects across the birth-weight distribution, but low-weight births experienced the largest reductions. While our estimates may provide lower bounds— they are net of health benefits from reduced exposure to other pesticides—they suggest that glyphosate exposure accounted for 27-45% of the birth-weight decline rural counties experienced in the past twenty years.


#### **The Distributional Impacts of Climate Change across U.S. Local Labor Markets** with [John Morehouse](https://www.johnmmorehouse.com/)  

Climate change has affected households around the globe, but its impacts are not homogenous across space. We show that climate change has thus far disproportionately exposed disadvantaged demographic groups. However, household adaptation also impacts the welfare consequences of this unequal burden. We develop and estimate a new spatial equilibrium model of local labor markets, allowing households to adapt to climate change by choosing their city, energy consumption, and housing. We then simulate counterfactual climates and decompose the value of each adaptation mechanism. The lowest income decile has welfare effects an order of magnitude larger than the highest income decile. Additionally, Black households are worse off by $1.5\%$ of income relative to white households due to climate change to-date, and we project that gap to grow by an additional $5-7\%$ by the end of the century.

#### **Means Tested Solar Subsidies** with [Mark Colas](https://sites.google.com/site/markyaucolas/home)