---
title: "Emmett Saulnier"
output: rmdformats::html_docco
---

## About  
I am a 4th year PhD student at the University of Oregon studying economics. My research interests include environmental, urban, health, and climate economics.

---

## Education

Ph.D. Economics, University of Oregon, *expected 2024*  
M.S. Economics, University of Oregon, 2020  
B.A. Economics, University of Virginia, 2017  
B.S. Commerce, University of Virginia, 2017

---

## Working papers 

**Vertical Migration Externalities**  
Mark Colas and Emmett Saulnier  


---

## Research in Progress  

**Optimal Solar Subsidies**  
Mark Colas and Emmett Saulnier  

**Perinatal health effects of herbicides: Glyphosate, Roundup, and the rollout of GM crops**  
Edward Rubin and Emmett Saulnier  

**The Distributional Impacts of Climate Change across U.S. Local Labor Markets**  
John Morehouse and Emmett Saulnier  

---

## Teaching  


**EC 434/534: Environmental Economics**, U.O. Winter 2023  
Instructor of record for upper level undergraduate/masters environmental economics course     
**EC 320: Introduction to Econometrics**, U.O. Spring 2022  
Instructor of record for first course in undergradute econometrics sequence  
**EC 421: Introduction to Econometrics**, U.O. Winter 2022  
Led lab section for upper level undergraduate econometrics class  
**EC 607: Core Microeconomics III**, U.O. Spring 2021   
Led discussion section for 1st year PhD students covering topics in game theory and general equilibrium  
**EC 607: Core Microeconomics II**, U.O. Winter 2021  
Led discussion section for 1st year PhD students covering topics in producer theory and partial equilibrium  


---

## Professional Experience  

**Research Assistant, Dr. Meredith Fowlie and Dr. Edward Rubin** Eugene, OR 2021  
Built a machine learning model to predict air pollution levels using a chemical transport model and weather data.  
**Senior Business Analyst, CarMax** Richmond, Va 2019  
Built a machine learning model that informed operational strategy and analyzed experiments to prove its value.   
**Business Analyst, CarMax** Richmond, Va 2017-2019  
Worked on a multidisciplinary team of marketing strategists, software engineers, and data analysts to improve carmax.com's visibility in search engine results.  
**Feeds and Search Engine Marketing Intern, Merkle** Charlottesville, Va 2016   
Optimized product feeds for online retail clients to be sent to various search and comparison shopping engines

---

## Presentations  

**2023** *(including scheduled)* Freddie Mac, Western Economic Association International (WEAI) Annual Conference  
**2022** Western Economic Association International (WEAI) Annual Conference, Seminar of Water and Environmental Economics Online (SWELL), The Workshop in Environmental Economics and Data Science (TWEEDS)  

**2021** Berkeley/Sloan Summer School in Environmental and Energy Economics  

---  

## Honors and Awards  

Kleinsorge Summer Research Fellowship 2022  
Dale Underwood Outstanding Graduate Student Scholarship, 2020  
Best 1st Year Econometrics Performance, 2020  
First Year Fellowship, 2019-2020

---   

## Skills 
**Computing:** R, SQL, Julia  
**Visual:** Tableau, $\LaTeX$, Markdown  


---  

## Contact  
**Email:** emmetts@uoregon.edu  
**Website:** https://www.emmettsaulnier.com  
**Github:** [emmettsaulnier](https://github.com/emmettsaulnier)


```{R generate pdfs, include = F, eval = F}
#remotes::install_github('rstudio/pagedown')
library(pagedown)
pagedown::chrome_print("saulnier_cv.html", output = "saulnier_cv.pdf")
```


